### ISSUE TITLE
pip install monthdelta too

### ISSUE THREAD

**Issue by llorracc** [mrooney/mintapi#126]
Just did a fresh install of everything and the one thing I needed to do that is not in the instructions was install the monthdelta package.

**Comment by mrooney** [comment]
Hey there, I don't have that package installed and haven't run in to issues, and don't see it being used. Can you clarify where the error is when you encounter this?

**Comment by llorracc** [comment]
I should have preserved the logfile, but didn't -- now that it's fixed, I don't have it.

On my existing anaconda2 installation, I was running into the "timeout" error and couldn't figure out how to fix it, finally gave up and installed a totally fresh version of anaconda3, installed selenium and chromedriver and keyring etc and absolutely nothing else.  And got a crash that told me I needed monthdate.  Installed it, and presto everything worked.

**Comment by mrooney** [comment]
Thanks for your time in creating the report and responding! If you figure out the log later, let me know, otherwise I'll close it for now. Looking at https://pypi.python.org/pypi/MonthDelta, I can see that it provides a MonthDelta class and monthmod function, neither of which are referenced in the codebase, and I can also see via `pip freeze` that I don't have it installed and am not having any issues. So I'd just need more data to figure out where this is possibly coming from :)
